Repository alx3416/CienciaDatos2024-1, pull requests merged in 2024-02, with the labels that each got.

#1 Añadimos funcion 3
  main.py
Labels: enhancement

#3 Setup Inicial y declaración de funciones básicas
  .gitignore
  data/diabetes.tab.txt
  main.py
  notebooks/Hola_mundo.ipynb
  qr-code-drive.png
  requirements.txt
  utils/imports.py
  utils/processing.py
  utils/visuals.py
Labels: good first issue

#4 adding function to read diabetes dataset
  .gitignore
  utils/processing.py
  utils/visuals.py
Labels: good first issue

#11 Feature/generate histograms
  utils/visuals.py
Labels: documentation, enhancement

#12 Feature/save all correlations into one image
  main.py
  utils/processing.py
  utils/visuals.py
Labels: enhancement

#23 input_output_logigistic
  main.py
Labels: enhancement
